version: '3.8'

services:
  kronos:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    image: kronos-dev:0.0.1
    container_name: kronos-server
    ports:
      - '5000:8080'
    volumes:
      - .:/app
