version: '3.8'

services:
  dgraph-zero:
    image: dgraph/dgraph:latest
    volumes:
      - type: volume
        source: dgraph-zero
        target: /dgraph
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=dgraph-zero:5080

  dgraph-alpha:
    image: dgraph/dgraph:latest
    volumes:
      - type: volume
        source: dgraph-alpha
        target: /dgraph
    ports:
      - 8081:8080
      - 9080:9080
    restart: on-failure
    command: dgraph alpha --my=dgraph-alpha:7080 --zero=dgraph-zero:5080
    depends_on:
      - dgraph-zero

  ratel:
    image: dgraph/ratel:latest
    ports:
      - 8000:8000
    command: dgraph-ratel
    depends_on:
      - dgraph-alpha

  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:latest
    ports:
    - 8082:8080
    - 50051:50051
    volumes:
    - weaviate:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'node1'

  kronos:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    image: kronos-dev
    container_name: kronos-server
    ports:
      - '5000:8080'
    depends_on:
      - dgraph-zero
      - dgraph-alpha
      - weaviate

volumes:
  dgraph-zero:
  dgraph-alpha:
  weaviate:
